### ISSUE TITLE
Token does not authenticate on first load

### ISSUE THREAD

**Issue by 2600box** [rclone/rclone-webui-react#27]
Tested this on both windows and MacOS with Chrome with the same behaviour confirmed. Did not test other browsers.

Upon launching the command `rclone rcd --rc-web-gui` a Chrome page is automatically opened and an error page is displayed. The url takes the format: `http://gui:#rando_passwd@127.0.0.1:5572/?login_token=#rando_token%3D#/login`

and the error page suggests: "Something went wrong.
Try refreshing the page. If the issue persists, please consider opening a new issue on our Github page."

Reloading the page did nothing, removing the 'login' suffix allowed the page to load. After some expimerimentation I identified that it is not the login suffix, but rather it is necessary to select the URL and hit enter to load the page. 'Reload' in Chrome does not work in this case. 

Once in the gui, subsequent restarts of the rclone process login as intended.

This can be reproduced by clicking logout on web-gui and restarting the rlcone process, which will present the error page again.

```2019/09/10 09:00:00 DEBUG : rclone: Version "v1.49.2" starting with parameters ["rclone" "rcd" "--rc-web-gui" "--log-file" "/Users/rlcone/Desktop/web-gui.log" "--log-level" "DEBUG"]
2019/09/10 09:00:00 NOTICE: Required files exist. Skipping download
2019/09/10 09:00:00 INFO  : Using default username: gui 
2019/09/10 09:00:00 INFO  : No password specified. Using random password: #rando_passwd 
2019/09/10 09:00:00 INFO  : Using --user gui --pass XXXX as authenticated user
2019/09/10 09:00:00 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/09/10 09:00:00 DEBUG : login_token "#rando_token"
2019/09/10 09:00:04 DEBUG : rc: "core/stats": with parameters map[]
2019/09/10 09:00:04 DEBUG : rc: "core/stats": reply map[bytes:0 checks:0 deletes:0 elapsedTime:0 errors:0 fatalError:false retryError:false speed:0 transfers:0]: <nil>
2019/09/10 09:00:04 DEBUG : rc: "core/stats": with parameters map[]
2019/09/10 09:00:04 DEBUG : rc: "core/stats": reply map[bytes:0 checks:0 deletes:0 elapsedTime:0 errors:0 fatalError:false retryError:false speed:0 transfers:0]: <nil>
2019/09/10 09:00:04 DEBUG : rc: "core/bwlimit": with parameters map[]
2019/09/10 09:00:04 DEBUG : rc: "core/bwlimit": reply map[bytesPerSecond:-1 rate:off]: <nil>
```

**Comment by ncw** [comment]
> Tested this on both windows and MacOS with Chrome with the same behaviour confirmed. Did not test other browsers.

I can't replicate this on Linux with Chrome...

@negative0 have you got access to macOS/Windows to try this?

Could this be some extension you have loaded interfering?

**Comment by negative0** [comment]
I was able to replicate this on Linux + Chromium. 

This is what the browser console shows:

```
DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://127.0.0.1:5572/' cannot be created in a document with origin 'http://127.0.0.1:5572' and URL 'http://gui:sRmCEUfXZqRQQmxdRrHm3g@127.0.0.1:5572/?login_token=Z3VpOnNSbUNFVWZYWnFSUVFteGRSckhtM2c%3D#/login'.
    at I (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/3.d9cec7dd.chunk.js:1:753)
    at a.value (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/3.d9cec7dd.chunk.js:1:2465)
    at Wa (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:266546)
    at Ha (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:269222)
    at http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282451
    at Object.t.unstable_runWithPriority (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:293197)
    at Nu (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282386)
    at ju (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282162)
    at Cu (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:281507)
    at Tu (http://gui:_2Rm3_nDJTH3pVfe-A9mQg@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:280528)
pa @ react-dom.production.min.js:4408

```

I havent able to pinpoint the issue yet. Working on it.

**Comment by hyxxsfwy** [comment]
Replicate the same issue, Windows10 + Chrome 77.0.3865.90

**Comment by systemmonkey42** [comment]
Windows 10 - latest build (0.0.8)

This is still happening;  The error in the browser console is as follows
﻿
react-dom.production.min.js:4408 DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://127.0.0.1:5572/' cannot be created in a document with origin 'http://127.0.0.1:5572' and URL 'http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/?login_token=Z3VpOmhES0lLb3ZLcDVKNlNMeGRzN25seFE%3D#/login'.
    at I (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/3.d9cec7dd.chunk.js:1:753)
    at a.value (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/3.d9cec7dd.chunk.js:1:2465)
    at Wa (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:266545)
    at Ha (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:269221)
    at http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282450
    at Object.t.unstable_runWithPriority (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:293196)
    at Nu (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282385)
    at ju (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:282161)
    at Cu (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:281506)
    at Tu (http://gui:hDKIKovKp5J6SLxds7nlxQ@127.0.0.1:5572/static/js/6.be243fa8.chunk.js:1:280527)
ErrorBoundary.js:22 Hey
manifest.json:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
﻿

As mentioned in the first message, pressing F5 repeats the error.   Selecting the URL in the address bar and pressing enter works.

​

**Comment by redtux** [comment]
Just reproduced this with Chromium Version 76.0.3809.100 running on Ubuntu 19.04 (64-Bit).

```
rclone rcd --rc-web-gui
2019/10/20 16:50:33 NOTICE: A new release for gui is present at https://github.com/rclone/rclone-webui-react/releases/download/v0.0.8/currentbuild.zip
2019/10/20 16:50:33 NOTICE: Downloading webgui binary. Please wait. [Size: 4646512, Path :  /home/redtux/.cache/rclone/webgui/v0.0.8.zip]
2019/10/20 16:50:48 NOTICE: Unzipping
2019/10/20 16:50:48 NOTICE: Serving remote control on http://127.0.0.1:5572/
```

On the first run I get an error, while the second run works fine.

```
rclone rcd --rc-web-gui
2019/10/20 16:52:36 NOTICE: Required files exist. Skipping download
2019/10/20 16:52:36 NOTICE: Serving remote control on http://127.0.0.1:5572/
```
