### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by ridhishjain** [rclone/rclone-webui-react#60]
I am a windows 10 user and running npm install is throwing this error:
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\gsoc\cc-extractor\rclone\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (F:\\gsoc\\cc-extractor\\rclone\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (F:\\gsoc\\cc-extractor\\rclone\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (F:\\gsoc\\cc-extractor\\rclone\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at F:\\gsoc\\cc-extractor\\rclone\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at F:\\gsoc\\cc-extractor\\rclone\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at F:\\gsoc\\cc-extractor\\rclone\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
```

what should I do to solve this problem?

**Comment by hjyoung1** [comment]
Maybe this. 
https://stackoverflow.com/a/53009640

**Comment by ridhishjain** [comment]
that doesn't seem to fox the error.....I tried `npm outdated` and there are a lot of packages that need to be updated in order for the site to work properly and not throw errors in future. Here's the log:
```
Package                  Current   Wanted          Latest  Location
node-sass                MISSING   4.13.1          4.13.1  @rclone/rclone-webui
@coreui/coreui            2.1.12   2.1.16          2.1.16  @rclone/rclone-webui
@coreui/icons              0.3.0    0.3.0           1.0.1  @rclone/rclone-webui
@coreui/react              2.5.1    2.5.4           2.5.4  @rclone/rclone-webui
axios                     0.19.0   0.19.2          0.19.2  @rclone/rclone-webui
bootstrap                  4.3.1    4.4.1           4.4.1  @rclone/rclone-webui
chart.js                   2.8.0    2.9.3           2.9.3  @rclone/rclone-webui
core-js                    3.1.4    3.6.4           3.6.4  @rclone/rclone-webui
coveralls                  3.0.4    3.0.9           3.0.9  @rclone/rclone-webui
enzyme                    3.10.0   3.11.0          3.11.0  @rclone/rclone-webui
enzyme-adapter-react-16   1.14.0   1.15.2          1.15.2  @rclone/rclone-webui
enzyme-to-json             3.3.5    3.4.4           3.4.4  @rclone/rclone-webui
fetch-mock                 7.3.6    7.7.3    9.0.0-beta.2  @rclone/rclone-webui
flag-icon-css              3.3.0    3.4.6           3.4.6  @rclone/rclone-webui
lodash                   4.17.14  4.17.15         4.17.15  @rclone/rclone-webui
react                     16.8.6  16.12.0         16.12.0  @rclone/rclone-webui
react-app-polyfill         1.0.1    1.0.6           1.0.6  @rclone/rclone-webui
react-awesome-player       1.0.9   1.0.11          1.0.11  @rclone/rclone-webui
react-chartjs-2            2.7.6    2.9.0           2.9.0  @rclone/rclone-webui
react-dnd                  7.7.0    7.7.0          10.0.2  @rclone/rclone-webui
react-dnd-html5-backend    7.7.0    7.7.0          10.0.2  @rclone/rclone-webui
react-dnd-test-backend     7.7.0    7.7.0          10.0.2  @rclone/rclone-webui
react-dnd-test-utils       7.7.0    7.7.0          10.0.2  @rclone/rclone-webui
react-dom                 16.8.6  16.12.0         16.12.0  @rclone/rclone-webui
react-in-viewport         0.0.38   0.0.38  1.0.0-alpha.11  @rclone/rclone-webui
react-redux                7.1.0    7.1.3           7.1.3  @rclone/rclone-webui
react-router-config        5.0.1    5.1.1           5.1.1  @rclone/rclone-webui
react-router-dom           5.0.1    5.0.1           5.1.2  @rclone/rclone-webui
react-scripts              3.0.1    3.3.1           3.3.1  @rclone/rclone-webui
react-test-renderer       16.8.6  16.12.0         16.12.0  @rclone/rclone-webui
react-toastify             5.3.1    5.5.0           5.5.0  @rclone/rclone-webui
reactstrap                 8.0.0    8.4.1           8.4.1  @rclone/rclone-webui
redux                      4.0.4    4.0.5           4.0.5  @rclone/rclone-webui
redux-mock-store           1.5.3    1.5.4           1.5.4  @rclone/rclone-webui
typescript                 3.5.3    3.7.5           3.7.5  @rclone/rclone-webui
```

I am upgrading all these and sending a PR corresponding to that
